name: weather_forecast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  awesome_notifications: ^0.10.1
  awesome_notifications_core: ^0.10.1
  awesome_notifications_fcm: ^0.10.1
  dio: ^5.8.0+1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  get: ^4.7.2
  http_mock_adapter: ^0.6.1
  logger: ^2.5.0
  objectbox: ^4.1.0
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.2
  slang: ^4.5.0
  slang_flutter: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

dependency_overrides:
  intl: ^0.20.0

flutter:
  uses-material-design: true
