name: weather_forecast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  awesome_notifications: ^0.10.1
  awesome_notifications_core: ^0.10.1
  awesome_notifications_fcm: ^0.10.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  get: ^4.7.2
  shared_preferences: ^2.5.2
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.20.0

flutter:
  uses-material-design: true
